import { chromium } from '@playwright/test';
const BASE='http://localhost:4182';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const page = await browser.newPage({ viewport:{width:390,height:844} });
await page.goto(`${BASE}/`);
await page.getByTestId('start-button').waitFor({timeout:20000});
await page.getByTestId('start-button').click();
await page.getByTestId('prologue-monologue').click();
const k = page.getByTestId('kaos-intro');
for (let i=0;i<6;i++) await k.click();
await page.getByTestId('world-clock').waitFor();
const devVisible = await page.getByTestId('dev-admin-entry').isVisible();
console.log('DEV entry visible:', devVisible);
await page.getByTestId('dev-admin-entry').click();
await page.getByTestId('dev-lock-input').fill('0909');
await page.getByTestId('dev-lock-submit').click();
await page.getByTestId('dev-admin-screen').waitFor({timeout:10000});
await page.getByTestId('preset-REUNITED').click();
await page.getByTestId('dev-playtest-summary').waitFor();
console.log('playtest panel:', (await page.getByTestId('dev-playtest-summary').innerText()).slice(0,60).replace(/\n/g,' | '));
await browser.close();
process.exit(devVisible ? 0 : 1);
